import type { Metadata } from "next";
import { Geist, Geist_Mono, Josefin_Sans, Josefin_Slab, Smooch, Smooch_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const josefinSans = Josefin_Sans({
    variable: "--font-josefin-sans",
    subsets: ["latin"]
});

const josefinSlab = Josefin_Slab({
    variable: "--font-josefin-slab",
    subsets: ["latin"]
});

const smoochSans = Josefin_Sans({
    variable: "--smooch-sans",
    subsets: ["latin"]
});

const smooch = Josefin_Slab({
    variable: "--smooch",
    subsets: ["latin"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${smoochSans.variable} ${smooch.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
