import type { Metadata } from "next";
import { Josefin_Sans, Josefin_Slab, Barlow_Semi_Condensed, Share_Tech_Mono } from "next/font/google";
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const josefinSans = Josefin_Sans({
    variable: "--font-josefin-sans",
    subsets: ["latin"]
});

const josefinSlab = Josefin_Slab({
    variable: "--font-josefin-slab",
    subsets: ["latin"]
});

const barlowSemiCondensed = Barlow_Semi_Condensed({
    variable: "--font-barlow-semi-condensed",
    subsets: ["latin"],
    weight: "400"
})

const shareTechMono = Share_Tech_Mono({
    variable: "--font-share-tech-mono",
    subsets: ["latin"],
    weight: "400"
})
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    {/*<body
        className={`${josefinSans.variable} ${josefinSlab.variable} ${barlowSemiCondensed.variable} ${shareTechMono.variable} antialiased`}
      >
        {children}
      </body>*/}
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
